import sys
import os
myDir = os.getcwd()
sys.path.append(myDir)

from Controllers.UsuariosControllers import UsuariosControllers
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_usuarios(object):
    
    def __init__(self):
        self.ui_usuario = UsuariosControllers(self)         


    def setupUi(self, Form_usuarios):
        Form_usuarios.setObjectName("Form_usuarios")
        Form_usuarios.resize(764, 503)
        Form_usuarios.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.checkBox_crearEvento = QtWidgets.QCheckBox(parent=Form_usuarios)
        self.checkBox_crearEvento.setGeometry(QtCore.QRect(480, 59, 111, 31))
        self.checkBox_crearEvento.setObjectName("checkBox_crearEvento")
        self.checkBox_inscripciones = QtWidgets.QCheckBox(parent=Form_usuarios)
        self.checkBox_inscripciones.setGeometry(QtCore.QRect(610, 100, 111, 31))
        self.checkBox_inscripciones.setObjectName("checkBox_inscripciones")
        self.checkBox_cronograma = QtWidgets.QCheckBox(parent=Form_usuarios)
        self.checkBox_cronograma.setGeometry(QtCore.QRect(610, 60, 111, 31))
        self.checkBox_cronograma.setObjectName("checkBox_cronograma")
        self.checkBox_tickets = QtWidgets.QCheckBox(parent=Form_usuarios)
        self.checkBox_tickets.setGeometry(QtCore.QRect(480, 140, 111, 31))
        self.checkBox_tickets.setObjectName("checkBox_tickets")
        self.checkBox_configuracion = QtWidgets.QCheckBox(parent=Form_usuarios)
        self.checkBox_configuracion.setGeometry(QtCore.QRect(480, 100, 121, 31))
        self.checkBox_configuracion.setObjectName("checkBox_configuracion")
        self.label = QtWidgets.QLabel(parent=Form_usuarios)
        self.label.setGeometry(QtCore.QRect(480, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form_usuarios)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form_usuarios)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form_usuarios)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form_usuarios)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.plainTextEdit_nombre = QtWidgets.QPlainTextEdit(parent=Form_usuarios)
        self.plainTextEdit_nombre.setGeometry(QtCore.QRect(180, 20, 251, 31))
        self.plainTextEdit_nombre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_nombre.setObjectName("plainTextEdit_nombre")
        self.plainTextEdit_correo = QtWidgets.QPlainTextEdit(parent=Form_usuarios)
        self.plainTextEdit_correo.setGeometry(QtCore.QRect(180, 100, 251, 31))
        self.plainTextEdit_correo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_correo.setObjectName("plainTextEdit_correo")
        self.plainTextEdit_usuario = QtWidgets.QPlainTextEdit(parent=Form_usuarios)
        self.plainTextEdit_usuario.setGeometry(QtCore.QRect(180, 150, 251, 31))
        self.plainTextEdit_usuario.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_usuario.setObjectName("plainTextEdit_usuario")
        self.plainTextEdit_contrasena = QtWidgets.QPlainTextEdit(parent=Form_usuarios)
        self.plainTextEdit_contrasena.setGeometry(QtCore.QRect(180, 200, 251, 31))
        self.plainTextEdit_contrasena.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_contrasena.setObjectName("plainTextEdit_contrasena")
        self.tableWidget_usuarios = QtWidgets.QTableWidget(parent=Form_usuarios)
        self.tableWidget_usuarios.setGeometry(QtCore.QRect(10, 270, 731, 221))
        self.tableWidget_usuarios.setStyleSheet("border-radius: 10px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.tableWidget_usuarios.setObjectName("tableWidget_usuarios")
        self.tableWidget_usuarios.setColumnCount(7)
        self.tableWidget_usuarios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuarios.setHorizontalHeaderItem(6, item)
        self.pushButton_eliminar = QtWidgets.QPushButton(parent=Form_usuarios)
        self.pushButton_eliminar.setGeometry(QtCore.QRect(690, 220, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.pushButton_eliminar.setFont(font)
        self.pushButton_eliminar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: rgb(255, 255, 255);")
        self.pushButton_eliminar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ic/eliminar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_eliminar.setIcon(icon)
        self.pushButton_eliminar.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_eliminar.setObjectName("pushButton_eliminar")
        self.pushButton_ingresar = QtWidgets.QPushButton(parent=Form_usuarios)
        self.pushButton_ingresar.setGeometry(QtCore.QRect(570, 220, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.pushButton_ingresar.setFont(font)
        self.pushButton_ingresar.setStyleSheet("border-radius: 10px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.pushButton_ingresar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ic/mas (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_ingresar.setIcon(icon1)
        self.pushButton_ingresar.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_ingresar.setObjectName("pushButton_ingresar")
        self.pushButton_editar = QtWidgets.QPushButton(parent=Form_usuarios)
        self.pushButton_editar.setGeometry(QtCore.QRect(630, 220, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.pushButton_editar.setFont(font)
        self.pushButton_editar.setStyleSheet("border-radius: 10px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_editar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ic/boligrafo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_editar.setIcon(icon2)
        self.pushButton_editar.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_editar.setObjectName("pushButton_editar")
        self.label_6 = QtWidgets.QLabel(parent=Form_usuarios)
        self.label_6.setGeometry(QtCore.QRect(20, 70, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.plainTextEdit_dni = QtWidgets.QPlainTextEdit(parent=Form_usuarios)
        self.plainTextEdit_dni.setGeometry(QtCore.QRect(180, 60, 251, 31))
        self.plainTextEdit_dni.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit_dni.setObjectName("plainTextEdit_dni")

        self.retranslateUi(Form_usuarios)
        QtCore.QMetaObject.connectSlotsByName(Form_usuarios)

    def retranslateUi(self, Form_usuarios):
        _translate = QtCore.QCoreApplication.translate
        Form_usuarios.setWindowTitle(_translate("Form_usuarios", "USUARIOS"))
        self.checkBox_crearEvento.setText(_translate("Form_usuarios", " CREAR EVENTO "))
        self.checkBox_inscripciones.setText(_translate("Form_usuarios", "INSCRIPCIONES"))
        self.checkBox_cronograma.setText(_translate("Form_usuarios", "CRONOGRAMA"))
        self.checkBox_tickets.setText(_translate("Form_usuarios", "TICKETS"))
        self.checkBox_configuracion.setText(_translate("Form_usuarios", "CONFIGURACION"))
        self.label.setText(_translate("Form_usuarios", "PERMISOS"))
        self.label_2.setText(_translate("Form_usuarios", "NOMBRE Y APELLIDO:"))
        self.label_3.setText(_translate("Form_usuarios", "CORREO:"))
        self.label_4.setText(_translate("Form_usuarios", "USUARIO:"))
        self.label_5.setText(_translate("Form_usuarios", "CONTRASEÑA:"))
        self.tableWidget_usuarios.setSortingEnabled(True)
        item = self.tableWidget_usuarios.horizontalHeaderItem(0)
        item.setText(_translate("Form_usuarios", "NOMBRE "))
        item = self.tableWidget_usuarios.horizontalHeaderItem(1)
        item.setText(_translate("Form_usuarios", "USUARIO"))
        item = self.tableWidget_usuarios.horizontalHeaderItem(2)
        item.setText(_translate("Form_usuarios", "CREAR"))
        item = self.tableWidget_usuarios.horizontalHeaderItem(3)
        item.setText(_translate("Form_usuarios", "INSCR."))
        item = self.tableWidget_usuarios.horizontalHeaderItem(4)
        item.setText(_translate("Form_usuarios", "CRON."))
        item = self.tableWidget_usuarios.horizontalHeaderItem(5)
        item.setText(_translate("Form_usuarios", "TICKETS"))
        item = self.tableWidget_usuarios.horizontalHeaderItem(6)
        item.setText(_translate("Form_usuarios", "CONFIG."))
        self.label_6.setText(_translate("Form_usuarios", "DNI:"))
